
spring: 
 h2:
  console:
   enabled: true
   
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
   
 datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password: 
  hikari: 
   connection-test-query: SELECT 1
   
 sql:
  init:
   platform: h2

 jpa: 
  database: H2
  show-sql: true
  generate-ddl: true
  hibernate:
   ddl-auto: validate
    
 flyway:
  baseline-on-migrate: true
  validate-on-migrate: true

logging:
  level:
    org:
      springframework:
        test: DEBUG

  